Repository Kybbe/fire-turtles, pull requests merged in 2022-04, with the labels that each got.

#50 updated menu item
  src/views/Menu.js
Labels: enhancement

#51 components/CartItem
  src/components/Cart.js
  src/components/CartItem.js
Labels: enhancement

#53 text update
  public/index.html
  src/App.css
Labels: enhancement

#59 cart item price change
  src/components/CartItem.js
Labels: bug

#64 localStorage
  src/components/Cart.js
  src/store/menuActions.js
  src/store/menuReducer.js
Labels: enhancement

#71 Updated status.js with navigation back to menu
  src/views/Status.js
Labels: bug, enhancement

#70 lots of small stuff
  src/App.css
  src/App.js
  src/components/Cart.js
  src/components/Navbar.js
  src/views/Menu.js
Labels: bug, enhancement, Above and Beyond
