Repository Kybbe/fire-turtles, pull requests merged in 2022-03, with the labels that each got.

#17 created Menu.js
  src/App.js
  src/views/Menu.js
Labels: New View

#19 Created Cart.js, added route to HOME
  src/App.js
  src/components/Cart.js
Labels: New Component

#20 added store stuff for cart & menu
  src/App.css
  src/App.js
  src/components/Cart.js
  src/components/Navbar.js
  src/store/menuActions.js
  src/store/menuReducer.js
  src/views/Menu.js
Labels: enhancement

#23 Added cart items and css +++ fixed spelling errors
  src/App.css
  src/components/Cart.js
  src/views/AboutUs.js
Labels: enhancement

#25 menu html
  src/views/Menu.js
Labels: enhancement

#31 prittyfied cart and menu, added cart button
  src/App.css
  src/App.js
  src/components/Cart.js
  src/views/Menu.js
Labels: enhancement

#32 fixed nav so it pretty :)
  src/App.css
  src/components/Navbar.js
Labels: enhancement

#33 fixed transparent background, made small css tweaks
  src/App.css
  src/App.js
  src/components/Cart.js
  src/components/Navbar.js
  src/views/AboutUs.js
Labels: enhancement

#35 fix addToCart reducer and made cart live :)
  src/components/Cart.js
  src/store/menuReducer.js
  src/views/Menu.js
Labels: enhancement
